azure:
  subscriptionID: 81dde535-61b4-442a-96e6-6e30c6e55039
  tenantID: e9ec4533-d130-4d00-a7c3-d85f1c750c5a
  region: westeurope
  countUpdateDomains: 5
  countFaultDomains: 2

create:
  resourceGroup: true
  vnet: true
  availabilitySet: false
  natGateway: false

# identity:
  # name: identity-name
  # resourceGroup: identity-resource-group

# natGateway:
#   ipAddresses:
#   - name: ip-name
#     resourceGroup: ip-resource-group
#   - name: ip-name
#     resourceGroup: ip-resource-group
#   ipAddressRanges:
#   - name: ip-range-name
#     resourceGroup: ip-range-resource-group
#   - name: ip-range-name
#     resourceGroup: ip-range-resource-group

resourceGroup:
  name: my-resource-group
  vnet:
    name: my-vnet
    # resourceGroup: vnet-resource-group
    cidr: 10.10.10.10/6
  subnet:
    serviceEndpoints: []

clusterName: test-namespace

networks:
  worker: 10.250.0.0/19

outputKeys:
  resourceGroupName: resourceGroupName
  vnetName: vnetName
  # vnetResourceGroup: vnet-resource-group
  subnetName: subnetName
  availabilitySetID: availabilitySetID
  availabilitySetName: availabilitySetName
  routeTableName: routeTableName
  securityGroupName: securityGroupName
  # identityID: managedIdentityID
  # identityClientID: managedIdentityClientID