machineClasses:
- name: class-1-zone
# labels:
#   foo: bar
  region: westeurope
  resourceGroup: my-resource-group
  zone: 1
  # identityID: /subscriptions/subscription-id/resourceGroups/resource-group-name/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name
  network:
    vnet: my-vnet
    subnet: my-subnet-in-my-vnet
    # vnetResourceGroup: my-vnet-resource-group
    # acceleratedNetworking: true
  tags:
    Name: shoot-crazy-botany
    kubernetes.io-cluster-shoot-crazy-botany: "1"
    kubernetes.io-role-node: "1"
  secret:
    clientID: ABCD
    clientSecret: ABCD
    subscriptionID: abc
    tenantID: abc
    cloudConfig: abc
  machineType: Standard_DS1_V2
  image:
    urn: "CoreOS:CoreOS:Stable:1576.5.0"
    #id: "/Subscriptions/4bfa08b6-bad8-4b8e-aa00-741c0a859e36/Providers/Microsoft.Compute/Locations/westus/Publishers/CoreOS/ArtifactTypes/VMImage/Offers/CoreOS/Skus/Stable/Versions/1576.5.0"
  osDisk:
    size: 50
    #type: Standard_LRS
  sshPublicKey: ssh-rsa AAAAB3...
- name: class-2-availability-set
  region: westeurope
  resourceGroup: my-resource-group
  network:
    vnet: my-vnet
    subnet: my-subnet-in-my-vnet
  availabilitySetID: /subscriptions/subscription-id/resourceGroups/resource-group-name/providers/Microsoft.Compute/availabilitySets/availablity-set-name
  tags:
    Name: shoot-crazy-botany
    kubernetes.io-cluster-shoot-crazy-botany: "1"
    kubernetes.io-role-node: "1"
  secret:
    clientID: ABCD
    clientSecret: ABCD
    subscriptionID: abc
    tenantID: abc
    cloudConfig: abc
  machineType: Standard_DS1_V2
  image:
    #urn: "CoreOS:CoreOS:Stable:1576.5.0"
    id: "/Subscriptions/4bfa08b6-bad8-4b8e-aa00-741c0a859e36/Providers/Microsoft.Compute/Locations/westus/Publishers/CoreOS/ArtifactTypes/VMImage/Offers/CoreOS/Skus/Stable/Versions/1576.5.0"
  osDisk:
    size: 50
    type: Standard_LRS
  sshPublicKey: ssh-rsa AAAAB3...
